# This is a basic workflow to help you get started with Actions
# This shit may or may not work

name: Haxe iOS Build

# Controls when the workflow will run, you can add back push if you want but I recommend keeping it off.
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
          
      - name: Bootstrap Procursus
        uses: w2599/procursus-action@main
        with:
          packages: zstd ldid xz-utils bzip2 lz4
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Add Procursus to PATH
        run: |
          # echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
  
      - name: Select Correct Xcode (14.2)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib git lime https://github.com/FNF-Mod-Porting/lime
          haxelib install openfl
          haxelib install format
          haxelib install hxp
          haxelib --never install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons
          haxelib install newgrounds 1.4.0
          haxelib set flixel 4.11.0
          haxelib set flixel-addons 2.11.0
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install actuate 
          haxelib install hxCodec
          haxelib list

      - name: Build Game
        run: |
          haxelib run lime build ios

      - uses: actions/upload-artifact@v2
        with:
          name: iOS Build
          path: export/release/ios
          if-no-files-found: warn
